import { Word } from "./types";

/**
 * Exports the word list from the language,
 * it is then the grammar of this project.
 */
export default [
    new Word("INDENTATION", / {4}/i),
    new Word("FLOAT", /[0-9]+\.[0-9]+/),
    new Word("INTEGER", /[0-9]+/),
    new Word("NONE", /\bNone\b/),
    new Word("FALSE", /\bFalse\b/),
    new Word("TRUE", /\bTrue\b/),
    new Word("IMPORT", /\bimport\b/),
    new Word("FROM", /\bfrom\b/),
    new Word("GLOBAL", /\bglobal\b/),
    new Word("IF", /\bif\b/),
    new Word("ELSE", /\belse\b/),
    new Word("ELIF", /\belif\b/),
    new Word("FOR", /\bfor\b/),
    new Word("WHILE", /\bwhile\b/),
    new Word("AS", /\bas\b/),
    new Word("RAISE", /\braise\b/),
    new Word("ASSERT", /\bassert\b/),
    new Word("TRY", /\btry\b/),
    new Word("EXCEPT", /\bexcept\b/),
    new Word("FINALLY", /\bfinally\b/),
    new Word("CLASS", /\bclass\b/),
    new Word("LAMBDA", /\blambda\b/),
    new Word("IS", /\bis\b/),
    new Word("NOT", /\bnot\b/),
    new Word("DEL", /\bdel\b/),
    new Word("PRINT", /\bprint\b/),
    new Word("AND", /\band\b/),
    new Word("OR", /\bor\b/),
    new Word("IN", /\bin\b/),
    new Word("RANGE", /\brange\b/),
    new Word("BREAK", /\bbreak\b/),
    new Word("PASS", /\bpass\b/),
    new Word("CONTINUE", /\bcontinue\b/),
    new Word("D_QUOTE", /\"/),
    new Word("S_QUOTE", /\'/),
    new Word("L_PAR", /\(/),
    new Word("R_PAR", /\)/),
    new Word("F_DEF", /\bdef\b/),
    new Word("F_RETURN", /\breturn\b/),
    new Word("DOT", /\./),
    new Word("COMMA", /\,/),
    new Word("COLON", /\:/),
    new Word("S_COLON", /\;/),
    new Word("SPACE", / +/),
    new Word("NEW_L", /\n/),
    new Word("EQ", /\=/),
    new Word("OP_PLUS", /\+/),
    new Word("OP_MINUS", /\-/),
    new Word("OP_MULT", /\*/),
    new Word("OP_DIV", /\//),
    new Word("LT", /</),
    new Word("GT", /</),
    new Word("BANG", /!/),
    new Word("IDENTIFIER", /[a-z]+/i),
] as Word[];
